name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Inject Secret into JavaScript
        run: |
          echo "const API_SECRET_KEY = '${{ secrets.API_SECRET_KEY }}';" > src/config.js
          # Ensure src/config.js is included in .gitignore to prevent committing it

      - name: Build Project
        run: npm run build  # Your build command here

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Or your build directory
